### ISSUE TITLE
Revealed API key in Program.cs

### ISSUE THREAD

**Issue by vtsman** [thisthat/lol-champion-builder#1]
Revealing your api key violates the Riot API terms as specified [here](https://developer.riotgames.com/terms). Fortunately, generating a new key is as simple as going to your Riot developer dashboard, and clicking on the "New API Key" button next to your developer API key. In the future, I'd recommend reading your API key from a text file, and adding said file to your .gitignore

**Comment by thisthat** [comment]
I didn't realize this! 
Thank you very much, I will fix this as soon as possible!
